name: mForm
author: StephanWagner
category: Forms
tags: [input, select, element, ajax, submit, validate]
docs: http://htmltweaks.com/mForm/Documentation
demo: http://htmltweaks.com/mForm
current: 0.2.5